site_name: Blockchain Labs

pages:
- Home: 'index.md'
- Labs: 
    - 'Transaction storage lab': 'labs/lab3.1.md'
    - 'Blockchain logging lab': 'labs/lab3.3.md'
- About: 'about.md'

#theme: readthedocs
